app/core/views.py
from flask import Blueprint, render_template, url_for, flash, redirect, current_app
from .models import Books, User, db
from app.core.forms import BookForm, RegistrationForm, LoginForm, ProfileUpdateForm
from flask_login import login_user, login_required, current_user, logout_user


main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('index.html')

@login_required
@main.route('/add_book', methods=['GET', 'POST'])
def add_book():
    '''A Method to add a book.'''
    form = BookForm()
    if form.validate_on_submit():
        current_app.logger.info(f'{current_user.user_id} is registering a book.')
        try:
            new_book = Books(title=form.title.data, author=form.author.data, genre=form.genre.data, start_date=form.start_date.data, end_date=form.end_date.data, status=form.status.data, rating=form.rating.data, user_id=current_user.user_id)
            db.session.add(new_book)
            db.session.commit()
            flash('Book Registered Successfully!')
            current_app.logger.info(f'{current_user.user_id} has registered a book successfully!')
        except Exception as e:
            flash('Error registering Books!')
            current_app.logger.error(f'Error registering: {e}')
        return redirect(url_for('main.my_books'))
    return render_template('add_book.html', form=form)

@main.route('/register', methods=['GET', 'POST'])
def register():
    '''A Method to register a user.'''
    form = RegistrationForm()
    if form.validate_on_submit():
        current_app.logger.info("New user attempting to register.")
        try:
            new_user = User(user_name=form.username.data, user_password=form.password.data)
            new_user.set_password(form.password.data)
            db.session.add(new_user)
            db.session.commit()
            flash('User registered.')
            current_app.logger.info("New user registered.")
        except Exception as e:
            flash(f"Error registering user: {e}")
            current_app.logger.error(f"Error registering user: {e}")
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form)

@main.route('/login', methods=['GET', 'POST'])
def login():
    '''A method to login a user.'''
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(user_name=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            current_app.logger.info(f"User {user.user_name} successfully logged in.")
            return redirect(url_for('main.home'))
        else:
            flash("Invalid username or password.")
            current_app.logger.info(f"Failed login attempt for username: {form.username.data}")
    return render_template('login.html', form=form)

@main.route('/my_books')
@login_required
def my_books():
    '''A Method to show all of a users books.'''
    user_books = Books.query.filter_by(user_id=current_user.user_id).all()
    return render_template('my_books.html', user_books=user_books)

@main.route('/edit_book/<int:book_id>', methods=['GET', 'POST'])
@login_required
def edit_book(book_id):
    '''A method to allow users to edit their own books.'''
    book = Books.query.get_or_404(book_id)
    if book.user_id != current_user.user_id:
        flash('Book does not exist.')
        return redirect(url_for('main.home'))
    
    form = BookForm(obj=book)
    if form.validate_on_submit():
        book.title = form.title.data
        book.author = form.author.data
        book.genre = form.genre.data
        book.start_date = form.start_date.data
        book.end_date = form.end_date.data
        book.status = form.status.data
        book.rating = form.rating.data
        db.session.commit()
        flash('Book updated successfully!')
        return redirect(url_for('main.my_books'))
    
    return render_template('edit_book.html', form=form)

@main.route('/all_books')
def all_books():
    '''A method to show all books and which user added the book.'''
    books = Books.query.all()
    return render_template('all_books.html', books=books)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been successfully logged out.')
    return redirect(url_for('main.home'))

@main.route('/update_profile', methods=['GET', 'POST'])
@login_required
def update_profile():
    user = User.query.get(current_user.user_id)

    form = ProfileUpdateForm(obj=user)
    
    if form.validate_on_submit():
        user.username = form.username.data
        user.set_password(form.password.data)
        db.session.commit()
        flash('Profile updated successfully!')
        return redirect(url_for('main.home'))
    
    return render_template('update_profile.html', form=form)
    

app/templates/add_book.html
{% extends 'base.html' %}

{% block content %}
<h2>Add Book</h2>
<form method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.title.label }}
        {{ form.title(size=32) }}
        {% if form.title.errors %}
            <ul class="errors">
                {% for error in form.title.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </p>
    <p>
        {{ form.author.label }}
        {{ form.author(size=32) }}
        {% if form.author.errors %}
        <ul class="errors">
            {% for error in form.author.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.genre.label }}
        {{ form.genre(size=32) }}
        {% if form.genre.errors %}
        <ul class="errors">
            {% for error in form.genre.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.start_date.label }}
        {{ form.start_date(size=32) }}
        {% if form.start_date.errors %}
        <ul class="errors">
            {% for error in form.start_date.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.end_date.label }}
        {{ form.end_date(size=32) }}
        {% if form.end_date.errors %}
        <ul class="errors">
            {% for error in form.end_date.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.status.label }}
        {{ form.status(size=32) }}
        {% if form.status.errors %}
        <ul class="errors">
            {% for error in form.status.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.rating.label }}
        {{ form.rating(size=32) }}
        {% if form.rating.errors %}
        <ul class="errors">
            {% for error in form.rating.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/all_books.html
{% extends 'base.html' %}

{% block content %}
<h2>All Books</h2>
<ul class="books">
    <a href="{{ url_for('main.my_books') }}" class="btn">My Books</a>
    {% for book in books %}
        <li>
            Title: {{ book.title }}
        </li>
        <li>
            Author: {{ book.author }}
        </li>
        <li>
            Genre: {{ book.genre }}
        </li>
        <li>
            Status: {{ book.status.value }}
        </li>
        <li>
            Rating: {{ book.rating }}
        </li>
        <li>
            Added By: {{ book.user.user_name }}
        </li>
        <li>
            ************************************************************************
        </li>

    {% endfor %}
</ul>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
   <meta charset="UTF-8">
   <title>Personal Library Management System</title>
 <link rel="stylesheet" href="../static/css/styles.css">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
    {% for message in get_flashed_messages() %}
        <div>{{ message }}</div>
    {% endfor %}
    <nav>
      <div class="navbar">
        <ul class="menu">
          <li><a href="{{ url_for('main.home') }}">Home</a></li>
          <li><a href="{{ url_for('main.my_books') }}">My Books</a></li>
          <li><a href="{{ url_for('main.all_books') }}">All Books</a></li>
        </ul>
        <ul class="user-info">
          {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('main.logout') }}">Logout</a></li>
            <li><a href="{{ url_for('main.update_profile') }}">Update Profile</a></li>
            <li class="user">Logged in as: {{ current_user.user_name }}</li>
          {% else %}
            <li><a href="{{ url_for('main.login') }}">Login</a></li>
            <li><a href="{{ url_for('main.register') }}">Register</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  <div>
    {% block content %}
    {% endblock %}
  </div>
  <footer>
    <ul>
      {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('main.logout') }}">Logout</a></li>
        <li><a href="{{ url_for('main.update_profile') }}">Update Profile</a></li>
      {% else %}
        <li><a href="{{ url_for('main.login') }}">Login</a></li>
        <li><a href="{{ url_for('main.register') }}">Sign Up</a></li>
      {% endif %}
      <li><a href="{{ url_for('main.all_books') }}">All Books</a></li>
      <li><a href="{{ url_for('main.my_books') }}">My Books</a></li>
    </ul>
  </footer>
</body>
</html>

app/templates/edit_book.html
{% extends 'base.html' %}

{% block content %}
<h2>Edit Book</h2>
<form method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.title.label }}<br>
        {{ form.title(size=32) }}
        {% if form.title.errors %}
        <ul class="errors">
            {% for error in form.title.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.author.label }}<br>
        {{ form.author(size=32) }}
        {% if form.author.errors %}
        <ul class="errors">
            {% for error in form.author.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.genre.label }}<br>
        {{ form.genre(size=32) }}
        {% if form.genre.errors %}
        <ul class="errors">
            {% for error in form.genre.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.start_date.label }}<br>
        {{ form.start_date(size=32) }}
        {% if form.start_date.errors %}
        <ul class="errors">
            {% for error in form.start_date.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.end_date.label }}<br>
        {{ form.end_date(size=32) }}
        {% if form.end_date.errors %}
        <ul class="errors">
            {% for error in form.end_date.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.status.label }}<br>
        {{ form.status(size=32) }}
        {% if form.status.errors %}
        <ul class="errors">
            {% for error in form.status.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.rating.label }}<br>
        {{ form.rating(size=32) }}
        {% if form.rating.errors %}
        <ul class="errors">
            {% for error in form.rating.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="des">
    <p>
Welcome to your Personal Library Management System! This intuitive platform is designed for book enthusiasts who want to effortlessly organize and manage their book collections. Here, you can add your favorite books, update their details, and keep track of your reading journey. Whether you're a casual reader or a serious bibliophile, our system is tailored to make your reading experience more enjoyable and organized. Start exploring and discover the joys of having your personal library at your fingertips!
    </p>
</div>

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}
        {% if form.username.errors %}
        <ul class="errors">
            {% for error in form.username.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}
        {% if form.password.errors %}
        <ul class="errors">
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.remember_me.label }}<br>
        {{ form.remember_me(size=32) }}
        {% if form.remember_me.errors %}
        <ul class="errors">
            {% for error in form.remeber_me.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/my_books.html
{% extends 'base.html' %}

{% block content %}
<h2>My Books</h2>

<ul class="books">
    <a href="{{ url_for('main.add_book') }}" class="btn">Add New Book</a>
    {% for book in user_books %}
    <li>
        Title: {{ book.title }}
    </li>
    <li>
        Author: {{ book.author }}
    </li>
    <li>
        Genre: {{ book.genre }}
    </li>
    <li>
        Start Date: {{ book.start_date }}
    </li>
    <li>
        End Date: {{ book.end_date }}
    </li>
    <li>
        Status: {{ book.status }}
    </li>
    <li>
        Rating: {{ book.rating }}
    </li>
    <li>
        <a href="{{ url_for('main.edit_book', book_id=book.id) }}" class="btn">Edit</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block content %}
<h2>Register</h2>
<form method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}
        {% if form.username.errors %}
        <ul class="errors">
            {% for error in form.username.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}
        {% if form.password.errors %}
        <ul class="errors">
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.confirm_password.label }}<br>
        {{ form.confirm_password(size=32) }}
        {% if form.confirm_password.errors %}
        <ul class="errors">
            {% for error in form.confirm_password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/update_profile.html
{% extends 'base.html' %}

{% block content %}
<h2>Update Profile</h2>
<form method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}
        {% if form.username.errors %}
        <ul class="errors">
            {% for error in form.username.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}
        {% if form.password.errors %}
        <ul class="errors">
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>
        {{ form.confirm_password.label }}<br>
        {{ form.confirm_password(size=32) }}
        {% if form.confirm_password.errors %}
        <ul class="errors">
            {% for error in form.confirm_password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}